### ISSUE TITLE
Mismatch is newlic web agent and plugin data

### ISSUE THREAD

**Issue by navidmomin** [s12v/newrelic-elasticsearch#12]
Can you guys explain the exact definition of 

1) indices.search.query_total
2) indices.search.query_time_in_millis

Kindly consider our problem 
total request landed in web is 28k i.e 500 approx request per sec

But this elasticsearch plugin says request per second in overview section is 2160 req per sec

So my question is hows that possible?
Is there something else we are misunderstanding or can u please explain how this plugin works, defination of important terms and key terms usefull for scalling for example 

How do i check request fulfilled by elasticsearch ?

**Comment by s12v** [comment]
@navidmomin, it's based on `GET _nodes/stats` elasticsearch API, more info here https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

Difference with the of number of requests in web can be because of each web request calls elasticsearch several times, for example.
