### ISSUE TITLE
versions reports a fractional number with one single version in a cluster

### ISSUE THREAD

**Issue by ghost** [s12v/newrelic-elasticsearch#9]
I have a cluster of 9 nodes, all at version 1.4.4 (and the cluster stats reports "versions" : [ "1.4.4" ],) but in NewRelic I see "0.999 versions". How is that possible?

same with number of nodes -> '8.99 nodes'

Thanks!

**Comment by s12v** [comment]
@abarbieri-vs, I have same issues. Looks pretty strange. Maybe NR processes values over time and introduces a floating point error.

**Comment by ghost** [comment]
thanks!... interesting... since the versions array stay the same (until I do perform an upgrade) then it must be some kind of rounding error in NR metrics time series...

**Comment by adecarolis** [comment]
@abarbieri-vs same issue for me

**Comment by dbaggott** [comment]
@adecarolis @abarbieri-vs -- New Relic reports on time-processed data and it would not surprise me at all if the values were subject to imprecision.

Not that there's another issue inherent to the NR platform that can cause unexpectedly low values and might be at play here.  The issue surrounds the following:
1. the agent collecting data runs on a schedule and sends data to NR every minute (implemented using `java.util.concurrent.ScheduledExecutorService#scheduleAtFixedRate`)
2. the data received by NR implicitly gets assigned to the current minute
3. collecting/processing/sending data is non-instantaneous

This means that if an agent takes, e.g., 250 ms to collect/send data to NR, the next run will start 1 minutes + 250 ms after the previous run started.  Slowly over time, the agent will start later and later in the current minute and eventually you are guaranteed that there will be a clock minute for which NR won't receive any data.

Importantly, NR treats absent values for a given minute as all 0s.  This issue periodically skews the data being displayed by NR and cause it to report unexpectedly low numbers.  The longer it takes the agent to collect/process data, the more apparent this issue will be...

This issue is [touched upon here](https://discuss.newrelic.com/t/how-to-report-yes-no-boolean-values-via-a-custom-plugin/4990).
